kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obj-nov6-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: obj-nov6-1-dsp-job
    namespace: obj-nov6-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: obj-nov6-1-imagestream-job-role
