apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: obj-nov6-1
  janus-idp.io/tekton: obj-nov6-1
  backstage.io/kubernetes-id: obj-nov6-1
  backstage.io/kubernetes-namespace: obj-nov6-1 
  app.kubernetes.io/part-of: obj-nov6-1
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
