apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: obj-nov6-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obj-nov6-1 
  name: obj-nov6-1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: obj-nov6-1 
