apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: obj-nov6-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/obj-nov6-1:700751a92aa4b891f0d705d2c2bd512ce8096139@sha256:5f55b351b0e589e6b11ee5d63f4376eaaa93c484c220d07c24fd2c5bde739394 # use pre-built to bootstrap 
          name: app-inference
